name: battleship_ar_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_unity_widget: ^2022.2.0
  battleship_client:
    path: ../battleship_client
  serverpod_flutter: ^1.1.1
  shared_preferences: ^2.1.2
  flutter_bloc: ^8.1.3
  routemaster: ^1.0.1
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
